### ISSUE TITLE
Unable to generate `data/tree/phyloT_tree.newick`

### ISSUE THREAD

**Issue by billbrod** [cduvallet/microbiomeHD#2]
At a certain point, I am told by the Makefile to `Go to http://phylot.biobyte.de/ and generate tree from data/tree/ncbi_ids.clean.for_phyloT. Press any key to continue once you've added the tree file in data/tree/phyloT_tree.newick`. When I go to that website, upload the `ncbi_ids.clean.for_phyloT` file, and click generate tree, I get the error `Error: At least 2 IDs are required to generate a tree.` Indeed, the file `ncbi_ids.clean.for_phyloT` only contains one number: `239934`. 

Was I supposed to click something on the phyloT website? I just uploaded the file and didn't change anything else.

**Comment by billbrod** [comment]
Whoops, turns out this is a different issue. It's because I don't have the commands `efetch`, `esearch`, and `xtract` on my machine.

**Comment by billbrod** [comment]
So it looks like they're from the [EDirect](https://dataguide.nlm.nih.gov/edirect/install.html#edirect-installation) package. I was able in my user directory following the directions on that website (no sudo required), so it's not an issue, but I would include a bit in your README about this.

**Comment by cduvallet** [comment]
Right, the README is unclear about this. I didn't know how to incorporate this non-Makefile-able step into the process. I actually include the final phyloT tree in the repo so that users don't have to do this time-consuming step (also because re-making the tree changes the order of genera, so doesn't reproduce my figures exactly). So if you just press enter, you can keep going and nothing will break (because only the final tree file is used in subsequent steps).

Maybe I'll edit the prompt at that step to say "unless you hardcore want to reproduce everything, you can ignore this step and just press enter, since the file is already in `data/tree`.

**Comment by billbrod** [comment]
Ah yeah, that would be a good idea then. But actually, things break when I press enter, I get the following:

```
src/analysis/update_tree.py data/tree/genera.tmp data/tree/phyloT_tree.newick data/tree/phyloT_tree.updated.newick
Traceback (most recent call last):
  File "src/analysis/update_tree.py", line 60, in <module>
    tree = dp.Tree.get(path=args.tree_in, schema='newick')
  File "/home/wfb229/for_claire/lib/python2.7/site-packages/dendropy/datamodel/treemodel.py", line 2735, in get
    return cls._get_from(**kwargs)
  File "/home/wfb229/for_claire/lib/python2.7/site-packages/dendropy/datamodel/basemodel.py", line 155, in _get_from
    return cls.get_from_path(src=src, schema=schema, **kwargs)
  File "/home/wfb229/for_claire/lib/python2.7/site-packages/dendropy/datamodel/basemodel.py", line 215, in get_from_path
    with open(src, "r", newline=None) as fsrc:
  File "/home/wfb229/for_claire/lib/python2.7/site-packages/dendropy/utility/filesys.py", line 60, in pre_py34_open
    buffering=buffering)
IOError: [Errno 2] No such file or directory: 'data/tree/phyloT_tree.newick'
make: *** [data/tree/phyloT_tree.updated.newick] Error 1
```

So I went ahead and copied the `phyloT_tree.updated.newick` file to `phyloT_tree.newick`, but that doesn't work either. But if I understand what you're saying, this step should just be skipped, right? It `phyloT_tree.updated.newick` is there and it's the creation of that file that's giving me an issue above?

I actually wasn't able to recreate the files anyway, having a similar issue to [this one](https://www.biostars.org/p/275761/), though the solution there doesn't fix it.

(For each of the genera, I get the following:
```
Cerasicoccus
501 Protocol scheme 'https' is not supported (LWP::Protocol::https not installed)
No do_post output returned from 'https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=taxonomy&term=Cerasicoccus&retmax=0&usehistory=y&edirect_os=linux&edirect=7.60&tool=edirect&email=wfb229@c99-01'
Result of do_post http request is
$VAR1 = bless( {
                 '_request' => bless( {
                                        '_headers' => bless( {
                                                               'user-agent' => 'libwww-perl/6.26',
                                                               'content-type' => 'application/x-www-form-urlencoded'
                                                             }, 'HTTP::Headers' ),
                                        '_method' => 'POST',
                                        '_uri' => bless( do{\(my $o = 'https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi')}, 'URI::https' ),
                                        '_content' => 'db=taxonomy&term=Cerasicoccus&retmax=0&usehistory=y&edirect_os=linux&edirect=7.60&tool=edirect&email=wfb229@c99-01'
                                      }, 'HTTP::Request' ),
                 '_content' => 'LWP will support https URLs if the LWP::Protocol::https module
is installed.
',
                 '_rc' => 501,
                 '_headers' => bless( {
                                        'client-warning' => 'Internal response',
                                        'content-type' => 'text/plain',
                                        'client-date' => 'Wed, 06 Dec 2017 20:30:23 GMT',
                                        '::std_case' => {
                                                          'client-warning' => 'Client-Warning',
                                                          'client-date' => 'Client-Date'
                                                        }
                                      }, 'HTTP::Headers' ),
                 '_msg' => 'Protocol scheme \'https\' is not supported (LWP::Protocol::https not installed)'
               }, 'HTTP::Response' );

WebEnv value not found in search output - WebEnv1 
Db value not found in fetch input
```

And I'm not really sure what to make of that)

**Comment by cduvallet** [comment]
Hm ok, I've included the pre-requisites for the tree (commits 070a90e93d4fee03d7986f9dfecff849adf9c176 and 11c7c237cd78fbace1481213375d6b2fc72eec5e), which will hopefully skip this step completely in the Makefile. (Hope I got them all, this part got complicated...)

Can you `git pull` for the updates, `touch data/tree/*` so that all files have the same timestamp (as will be the case when someone `git clone`s this updated repo), and try running `make` again?

**Comment by billbrod** [comment]
Okay, so I pulled, touched, ran make, and got the following error. It looks like there are duplicates within `phyloT_tree.updated.newick`?

```
python src/analysis/reorder_qvalues.py --do-qvals --qvalues data/analysis_results/qvalues.mean.kruskal-wallis.case-control.sig.txt data/tree/phyloT_tree.updated.newick
Traceback (most recent call last):
  File "src/analysis/reorder_qvalues.py", line 35, in <module>
    sig_otus = reorder_index_from_tree(args.fntree, sig_otus)
  File "/scratch/wfb229/microbiomeHD/src/util/Formatting.py", line 266, in reorder_index_from_tree
    tree = dp.Tree.get(path=fntree, schema='newick')
  File "/home/wfb229/for_claire/lib/python2.7/site-packages/dendropy/datamodel/treemodel.py", line 2735, in get
    return cls._get_from(**kwargs)
  File "/home/wfb229/for_claire/lib/python2.7/site-packages/dendropy/datamodel/basemodel.py", line 155, in _get_from
    return cls.get_from_path(src=src, schema=schema, **kwargs)
  File "/home/wfb229/for_claire/lib/python2.7/site-packages/dendropy/datamodel/basemodel.py", line 218, in get_from_path
    **kwargs)
  File "/home/wfb229/for_claire/lib/python2.7/site-packages/dendropy/datamodel/treemodel.py", line 2640, in _parse_and_create_from_stream
    global_annotations_target=None)
  File "/home/wfb229/for_claire/lib/python2.7/site-packages/dendropy/dataio/ioservice.py", line 362, in read_tree_lists
    global_annotations_target=global_annotations_target)
  File "/home/wfb229/for_claire/lib/python2.7/site-packages/dendropy/dataio/newickreader.py", line 325, in _read
    tree_factory=tree_factory):
  File "/home/wfb229/for_claire/lib/python2.7/site-packages/dendropy/dataio/newickreader.py", line 303, in tree_iter
    taxon_symbol_map_fn=taxon_symbol_mapper.require_taxon_for_symbol)
  File "/home/wfb229/for_claire/lib/python2.7/site-packages/dendropy/dataio/newickreader.py", line 385, in _parse_tree_statement
    is_internal_node=None)
  File "/home/wfb229/for_claire/lib/python2.7/site-packages/dendropy/dataio/newickreader.py", line 561, in _parse_tree_node_description
    is_internal_node=is_new_internal_node,
  File "/home/wfb229/for_claire/lib/python2.7/site-packages/dendropy/dataio/newickreader.py", line 561, in _parse_tree_node_description
    is_internal_node=is_new_internal_node,
  File "/home/wfb229/for_claire/lib/python2.7/site-packages/dendropy/dataio/newickreader.py", line 561, in _parse_tree_node_description
    is_internal_node=is_new_internal_node,
  File "/home/wfb229/for_claire/lib/python2.7/site-packages/dendropy/dataio/newickreader.py", line 561, in _parse_tree_node_description
    is_internal_node=is_new_internal_node,
  File "/home/wfb229/for_claire/lib/python2.7/site-packages/dendropy/dataio/newickreader.py", line 561, in _parse_tree_node_description
    is_internal_node=is_new_internal_node,
  File "/home/wfb229/for_claire/lib/python2.7/site-packages/dendropy/dataio/newickreader.py", line 561, in _parse_tree_node_description
    is_internal_node=is_new_internal_node,
  File "/home/wfb229/for_claire/lib/python2.7/site-packages/dendropy/dataio/newickreader.py", line 561, in _parse_tree_node_description
    is_internal_node=is_new_internal_node,
  File "/home/wfb229/for_claire/lib/python2.7/site-packages/dendropy/dataio/newickreader.py", line 677, in _parse_tree_node_description
    stream=nexus_tokenizer.src)
dendropy.dataio.newickreader.NewickReaderDuplicateTaxonError: Error parsing data source 'data/tree/phyloT_tree.updated.newick' on line 1 at column 54: Multiple occurrences of the same taxa on trees are not supported: trees with duplicate node labels can only be processed if the labels are not parsed as operational taxonomic unit concepts but instead as simply node labels by specifying 'suppress_internal_node_taxa=True, suppress_leaf_node_taxa=True'. Duplicate taxon labels: Clostridium_XIX
make: *** [data/analysis_results/qvalues.mean.kruskal-wallis.case-control.sig_ordered.txt] Error 1
```

And here's what my `phyloT_tree.updated.newick` looks like:

```
(((((((Fusobacterium,Cetobacterium,'Clostridium_XIX','Clostridium_XIX')Fusobacteriaceae,(Leptotrichia,Streptobacillus,Sneathia)Leptotrichiaceae)Fusobacteriales)Fusobacteriia)Fusobacteria,(((((Victivallis)Victivallaceae)Victivallales)Lentisphaeria,(((Oligosphaera)Oligosphaeraceae)Oligosphaerales)Oligosphaeria)Lentisphaerae,((((Coraliomargarita,Cerasicoccus)Puniceicoccaceae)Puniceicoccales)Opitutae,(((Akkermansia)Akkermansiaceae)Verrucomicrobiales)Verrucomicrobiae)Verrucomicrobia)PVC_group,(((((Deinococcus)Deinococcaceae)Deinococcales,((Thermus)Thermaceae)Thermales)Deinococci)'Deinococcus-Thermus',((((Tissierella)Tissierellaceae,(Parvimonas,Peptoniphilus,Murdochiella,Anaerococcus,Finegoldia,Gallicola,Anaerosphaera)Peptoniphilaceae)Tissierellales,(Dethiosulfatibacter,Sedimentibacter)unclassified_Tissierellia)Tissierellia,(((Holdemania,Turicibacter,Allobaculum,Eggerthia,Erysipelothrix,Catenibacterium,Bulleidia,Coprobacillus,Solobacterium,'Clostridium_XVIII','Erysipelotrichaceae_incertae_sedis','Clostridium_XVIII','Erysipelotrichaceae_incertae_sedis')Erysipelotrichaceae)Erysipelotrichales)Erysipelotrichia,(((Anaerovibrio,Centipeda,Selenomonas,Schwartzia,Megamonas,Mitsuokella)Selenomonadaceae)Selenomonadales,((Acidaminococcus,Phascolarctobacterium,Succinispira,Succiniclasticum)Acidaminococcaceae)Acidaminococcales,((Dialister,Anaeroglobus,Negativicoccus,Megasphaera,Allisonella,Veillonella)Veillonellaceae)Veillonellales)Negativicutes,(((Dolosigranulum,Granulicatella,Carnobacterium)Carnobacteriaceae,(Lactococcus,Streptococcus)Streptococcaceae,(Abiotrophia,Facklamia)Aerococcaceae,(Leuconostoc,Weissella)Leuconostocaceae,(Enterococcus,Tetragenococcus,Vagococcus)Enterococcaceae,(Lactobacillus,Pediococcus)Lactobacillaceae)Lactobacillales,((Viridibacillus,Solibacillus)Planococcaceae,(Bacillus,Anaerobacillus,Lysinibacillus)Bacillaceae,((Gemella)Bacillales_Family_XI._Incertae_Sedis)Bacillales_incertae_sedis,(Listeria)Listeriaceae,(Brevibacillus,Paenibacillus)Paenibacillaceae,(Macrococcus,Staphylococcus)Staphylococcaceae)Bacillales)Bacilli,(((Peptococcus,Dehalobacter)Peptococcaceae,(Lactonifactor,Oxobacter,Caminicella,Clostridium,Natronincola,Sarcina,Butyricicoccus,'Clostridium_sensu_stricto',Anaerobacter,'Clostridium_sensu_stricto',Anaerobacter)Clostridiaceae,(Anaerosporobacter,Shuttleworthia,Coprococcus,Roseburia,Dorea,Lachnobacterium,Butyrivibrio,Marvinbryantia,Acetitomaculum,Lachnospira,Robinsoniella,Lachnoanaerobaculum,Pseudobutyrivibrio,Johnsonella,Moryella,Hespellia,Cellulosilyticum,Oribacterium,Anaerostipes,Blautia,Syntrophococcus,Parasporobacterium,'Clostridium_XlVa','Clostridium_XlVb','Lachnospiracea_incertae_sedis',Ruminococcus2,'Clostridium_XlVa','Clostridium_XlVb','Lachnospiracea_incertae_sedis',Ruminococcus2)Lachnospiraceae,(Eubacterium,Acetobacterium,Anaerofustis,Pseudoramibacter)Eubacteriaceae,(Oscillibacter)Oscillospiraceae,(Natranaerovirga,Flavonifractor,Howardella,Pseudoflavonifractor)unclassified_Clostridiales,(Faecalibacterium,Acetanaerobacterium,Sporobacter,Ruminococcus,Saccharofermentans,Hydrogenoanaerobacterium,Anaerofilum,Acetivibrio,Gemmiger,Fastidiosipila,Subdoligranulum,Ethanoligenens,Papillibacter,Anaerotruncus,'Clostridium_III','Clostridium_IV','Clostridium_III','Clostridium_IV')Ruminococcaceae,((Guggenheimella,Fusibacter)Clostridiales_Family_XII._Incertae_Sedis,(Mogibacterium,Anaerovorax)Clostridiales_Family_XIII._Incertae_Sedis)Clostridiales_incertae_sedis,(Defluviitalea)Defluviitaleaceae,(Filifactor,Peptostreptococcus,Tepidibacter,'Clostridium_XI','Clostridium_XI')Peptostreptococcaceae,(Pelospora,Syntrophomonas)Syntrophomonadaceae,(Gracilibacter)Gracilibacteraceae,'Clostridium_XII','Clostridium_XII')Clostridiales)Clostridia)Firmicutes,((((Paraeggerthella,Eggerthella,Slackia,Adlercreutzia,Gordonibacter,Cryptobacterium,Asaccharobacter,Enterorhabdus)Eggerthellaceae)Eggerthellales,((Olsenella,Atopobium)Atopobiaceae,(Collinsella,Coriobacterium)Coriobacteriaceae)Coriobacteriales)Coriobacteriia,(((Dietzia)Dietziaceae,(Rhodococcus)Nocardiaceae,(Corynebacterium)Corynebacteriaceae)Corynebacteriales,((Geodermatophilus)Geodermatophilaceae)Geodermatophilales,((Propionibacterium)Propionibacteriaceae)Propionibacteriales,((Actinomyces,Actinobaculum,Arcanobacterium,Varibaculum,Mobiluncus)Actinomycetaceae)Actinomycetales,((Gardnerella,Bifidobacterium,Scardovia,Alloscardovia)Bifidobacteriaceae)Bifidobacteriales,((Brachybacterium)Dermabacteraceae,(Brevibacterium)Brevibacteriaceae,(Arthrobacter,Micrococcus,Kocuria,Nesterenkonia,Rothia)Micrococcaceae)Micrococcales)Actinobacteria)Actinobacteria,((Vampirovibrio)Candidatus_Melainabacteria)'Cyanobacteria/Melainabacteria group',((((Acholeplasma)Acholeplasmataceae)Acholeplasmatales,((Anaeroplasma,Asteroleplasma)Anaeroplasmataceae)Anaeroplasmatales,((Mycoplasma,Ureaplasma)Mycoplasmataceae)Mycoplasmatales)Mollicutes)Tenericutes)Terrabacteria_group,((((Cloacibacillus,Pyramidobacter,Jonquetella)Synergistaceae)Synergistales)Synergistia)Synergistetes,((((Bradyrhizobium)Bradyrhizobiaceae,(Methylobacterium)Methylobacteriaceae,(Ochrobactrum)Brucellaceae,(Phyllobacterium)Phyllobacteriaceae)Rhizobiales,((Insolitispirillum)Rhodospirillaceae,(Enhydrobacter)unclassified_Rhodospirillales)Rhodospirillales,((Rhodobacter,Paracoccus)Rhodobacteraceae)Rhodobacterales,((Novosphingobium,Sphingomonas,Sphingobium)Sphingomonadaceae)Sphingomonadales,((Phenylobacterium,Brevundimonas,Asticcacaulis,Caulobacter)Caulobacteraceae)Caulobacterales)Alphaproteobacteria,(((Methylobacillus)Methylophilaceae)Methylophilales,((Alcaligenes,Bordetella)Alcaligenaceae,(Comamonas,Acidovorax,Delftia,Polaromonas)Comamonadaceae,((Rhizobacter,Roseateles)Burkholderiales_Genera_incertae_sedis)unclassified_Burkholderiales,(Herbaspirillum,Herminiimonas,Oxalobacter)Oxalobacteraceae,(Ralstonia,Pandoraea)Burkholderiaceae,(Sutterella,Parasutterella)Sutterellaceae)Burkholderiales,((Kingella,Neisseria,Eikenella)Neisseriaceae)Neisseriales)Betaproteobacteria,(((Stenotrophomonas)Xanthomonadaceae)Xanthomonadales,((Aggregatibacter,Gallibacterium,Actinobacillus,Haemophilus,Pasteurella,Mannheimia)Pasteurellaceae)Pasteurellales,((Shewanella)Shewanellaceae)Alteromonadales,((Succinatimonas,Anaerobiospirillum,Succinivibrio)Succinivibrionaceae,(Aeromonas)Aeromonadaceae)Aeromonadales,((Obesumbacterium)Hafniaceae,(Erwinia,Pantoea)Erwiniaceae,(Shigella,Enterobacter,Salmonella,Buttiauxella,Pluralibacter,Cronobacter,Kluyvera,Klebsiella,Shimwellia,Citrobacter,Raoultella,'Escherichia/Shigella','Escherichia/Shigella')Enterobacteriaceae,(Lonsdalea,Dickeya)Pectobacteriaceae,(Providencia,Morganella,Xenorhabdus,Proteus)Morganellaceae,(Serratia,Yersinia)Yersiniaceae)Enterobacterales,((Pseudomonas)Pseudomonadaceae,((Moraxella)Moraxella,Acinetobacter)Moraxellaceae)Pseudomonadales)Gammaproteobacteria,((((Desulfomicrobium)Desulfomicrobiaceae,(Desulfovibrio,Bilophila)Desulfovibrionaceae)Desulfovibrionales)Deltaproteobacteria,(((Arcobacter,Campylobacter)Campylobacteraceae,(Helicobacter)Helicobacteraceae)Campylobacterales)Epsilonproteobacteria)'delta/epsilon subdivisions')Proteobacteria,((((Brachyspira)Brachyspiraceae)Brachyspirales,((Treponema,Sphaerochaeta)Spirochaetaceae)Spirochaetales)Spirochaetia)Spirochaetes,((((Elusimicrobium)Elusimicrobiaceae)Elusimicrobiales)Elusimicrobia)Elusimicrobia,((((((Pedobacter)Sphingobacteriaceae)Sphingobacteriales)Sphingobacteriia,(((Sediminibacterium)Chitinophagaceae)Chitinophagales)Chitinophagia,(((Phocaeicola)unclassified_Bacteroidales,(Odoribacter,Butyricimonas)Odoribacteraceae,(Hallella,Prevotella,Paraprevotella,Alloprevotella,Xylanibacter,Xylanibacter)Prevotellaceae,(Alistipes,Rikenella)Rikenellaceae,(Anaerophaga)Marinilabiliaceae,(Anaerorhabdus,Bacteroides)Bacteroidaceae,(Barnesiella,Tannerella,Parabacteroides,Dysgonomonas,Porphyromonas)Porphyromonadaceae)Bacteroidales)Bacteroidia,(((Ornithobacterium,Flavobacterium,Chryseobacterium,Elizabethkingia,Cloacibacterium,Planobacterium,Planobacterium)Flavobacteriaceae)Flavobacteriales)Flavobacteriia)Bacteroidetes)'Bacteroidetes/Chlorobi group')FCB_group,'Saccharibacteria_genera_incertae_sedis','Subdivision5_genera_incertae_sedis',GpI,'Saccharibacteria_genera_incertae_sedis','Subdivision5_genera_incertae_sedis',GpI)Bacteria,((Streptophyta)Viridiplantae)Eukaryota,(((((Methanosphaera,Methanobrevibacter,Methanobacterium)Methanobacteriaceae)Methanobacteriales)Methanobacteria,(((Methanomassiliicoccus)Methanomassiliicoccaceae)Methanomassiliicoccales)Thermoplasmata)Euryarchaeota)Archaea)cellular_organisms);
```

**Comment by cduvallet** [comment]
Hm okay, not sure why it's giving you that error but I think I'm trying to solve the wrong problem here.

I commented out the recipe to make the final tree file in the Makefile (070a90e93d4fee03d7986f9dfecff849adf9c176), so that the pre-requisites for the tree aren't checked and updated by `make`. It's super hacky but the most straightforward imo, since the majority of people shouldn't actually re-make the tree, since I include it as a pre-made file with the repo (but the method to make it should still be clear...)

**Comment by billbrod** [comment]
Okay, with those changes, `make` runs to completion!

Figures 10, 11, 15, and 16 aren't created. 15 and 16 aren't created because they're `rf_param_figures` and not included in `make all`, but I'm not sure about 10 and 11. There's a comment in the Makefile that says they should be created along with figure 9?

**Comment by cduvallet** [comment]
Woohoo!!

Figures 9, 10 and 11 in the paper are actually made as `figure9.alpha_diversity.chao1.pdf`, `figure9.alpha_diversity.shannon.pdf`, and `figure9.alpha_diversity.simpson.pdf`. Did those get made? (Again, hacky but whatever good enough!)

**Comment by billbrod** [comment]
Yup, I see all those figures! Woo!

**Comment by cduvallet** [comment]
🎉 

Thanks again!!!
